modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Customs;
use app\models\DeliveryForm;
use app\models\Feedback;
use app\models\Reviews;
use mdm\admin\models\form\Login;
use Yii;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {

        $delivery = DeliveryForm::find()->orderBy(['status' => 0])->limit(10)->all();
        $review = Reviews::find()->limit(4)->all();
        $del_count = DeliveryForm::find()->count();
        $cus_count = Customs::find()->count();
        $feed_count = Feedback::find()->count();
        $last = DeliveryForm::find()->orderBy(['id' => SORT_DESC])->one();
        $reviews = Reviews::find()->orderBy(['id' => SORT_DESC])->limit(4)->all();
        $feedback = Feedback::find()->orderBy(['id' => SORT_DESC])->limit(3)->all();
        return $this->render('index', compact([
            'delivery',
            'review',
            'del_count',
            'cus_count',
            'feed_count',
            'last',
            'reviews',
            'feedback'
        ]));
    }

    /**
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'login';
        $model = new Login();

        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
}

modules/admin/controllers/DeliveryFormController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\DeliveryForm;
use app\models\search\DeliveryFormSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DeliveryFormController implements the CRUD actions for DeliveryForm model.
 */
class DeliveryFormController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all DeliveryForm models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DeliveryFormSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DeliveryForm model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DeliveryForm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DeliveryForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing DeliveryForm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DeliveryForm model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DeliveryForm model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DeliveryForm the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DeliveryForm::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/views/default/index.php
<?php

use yii\helpers\Url;
?>

<!-- Start Page Content -->
<div class="row">
    <div class="col-md-3">
        <div class="card p-30">
            <div class="media">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-truck f-s-40 color-primary"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2><?=  $del_count ?></h2>
                    <p class="m-b-0">Total Delivery orders</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card p-30">
            <div class="media">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-sort-numeric-desc f-s-40 color-success"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2>000<?= $last->id ?></h2>
                    <p class="m-b-0">Last Delivery Number</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card p-30">
            <div class="media">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-envelope f-s-40 color-warning"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2><?= $feed_count ?></h2>
                    <p class="m-b-0">Feedback</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card p-30">
            <div class="media">
                <div class="media-left meida media-middle">
                    <span><i class="fa fa-user f-s-40 color-danger"></i></span>
                </div>
                <div class="media-body media-text-right">
                    <h2><?= $cus_count ?></h2>
                    <p class="m-b-0">Customer</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>Last Delivery Orders </h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Delivery №</th>
                            <th>Photo</th>
                            <th>Customer</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Created at</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                    <?php if(!empty($delivery)): ?>
                        <?php foreach ($delivery as $item): ?>
                        <tr>
                            <td> <a href="<?= Url::to(['delivery-form/view', 'id' => $item->id])?>">000<?= $item->id ?></a></td>
                            <td>
                                <div class="round-img">
                                   <img src="/uploads/<?= $item->cargo_img ?>" alt="">
                                </div>
                            </td>
                            <td><?= $item->customs->name ?></td>
                            <td><span><?= $item->name ?></span></td>
                            <td><span><?= $item->phone ?></span></td>
                            <td><span><?= date('d.m.Y H:m', $item->created_at)?></span></td>

                            <td><?php if($item->status == 1): ?>
                                <span class="badge badge-success">Done</span>
                                <?php else: ?>
                                <span class="badge badge-warning">Waiting</span>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                   <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-8">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Feedback </h4>
                    </div>
                    <div class="recent-comment">
                        <?php if(!empty($feedback)): ?>
                            <?php foreach ($feedback as $item): ?>
                            <div class="media">

                                <div class="media-body">
                                    <h4 class="media-heading"><?= $item->name ?></h4>
                                    <p><?= mb_substr($item->massege,0,150)?>..</p>
                                    <p class="comment-date"><?= date('d.m.Y H:m',$item->created_at) ?></p>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <!-- /# card -->
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card bg-dark">
            <div class="testimonial-widget-one p-17">
                <div class="testimonial-widget-one owl-carousel owl-theme">
                    <?php if(!empty($reviews)): ?>
                        <?php foreach ($reviews as $item): ?>
                     <div class="item">
                        <div class="testimonial-content">
                            <img class="testimonial-author-img" src="/uploads/<?= $item->path ?>" alt="" />
                            <div class="testimonial-author"><?= $item->name ?></div>
                            <div class="testimonial-author-position"><?= $item->email ?></div>

                            <div class="testimonial-text">
                                <i class="fa fa-quote-left"></i>  <?= mb_substr($item->review,0,150) ?>
                                <i class="fa fa-quote-right"></i>
                            </div>
                        </div>
                    </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- End PAge Content -->

modules/admin/views/default/login.php
<?php
/**
 * Created by PhpStorm.
 * User: Farhodjon
 * Date: 09.03.2018
 * Time: 16:50
 */

use yii\bootstrap\ActiveForm;

$this->title = 'Login to admin panel';

?>
<div class="unix-login">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <div class="login-content card">
                    <div class="login-form">
                        <h4>Login</h4>
                        <?php $form = ActiveForm::begin() ?>
                        <?= $form->field($model, 'username')->textInput() ?>
                        <?= $form->field($model, 'password')->passwordInput() ?>
                        <?= $form->field($model, 'rememberMe')->checkbox() ?>
                        <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Sign in</button>
                        <?php ActiveForm::end() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>